### ISSUE TITLE
Maybe stop recomending Epik

### ISSUE THREAD

**Issue by LytixDev** [LukeSmithxyz/landchad#136] opened 2021-09-29 20:10 UTC
On https://landchad.net/domain, Epik is used as an example of a domain registrar. I know Luke in the past recommended them. As I'm sure you're all aware they stored their costumers password in MD5, had really bad op-sec, and subsequently got hacked by anonymous. It took them a week to inform their users that their passwords had been leaked, when they knew this from day 1. It's a really bad idea to use Epik, and therefore it shouldn't be recommended to beginners IMO

**Comment by jotoho** [comment] 2021-09-29 20:25
I would say this is a duplicate of #132

**Closed** 2021-09-29 20:58 UTC
